package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/muzammil-cyber/golang-gin/dto"
	"github.com/muzammil-cyber/golang-gin/entity"
	"github.com/muzammil-cyber/golang-gin/graph/model"
)

// CreateVideo is the resolver for the createVideo field.
func (r *mutationResolver) CreateVideo(ctx context.Context, input model.CreateVideoInput) (*model.Video, error) {
	// Convert GraphQL input to DTO
	videoRequest := dto.VideoCreateRequest{
		Title:       input.Title,
		Description: input.Description,
		URL:         input.URL,
		Author: entity.Person{
			Name:  input.Author.Name,
			Age:   int(input.Author.Age),
			Email: input.Author.Email,
		},
	}

	// Call service
	createdVideo, err := r.VideoService.Save(videoRequest)
	if err != nil {
		return nil, fmt.Errorf("failed to create video: %w", err)
	}

	// Convert entity to GraphQL model
	return videoEntityToModel(&createdVideo), nil
}

// UpdateVideo is the resolver for the updateVideo field.
func (r *mutationResolver) UpdateVideo(ctx context.Context, id string, input model.UpdateVideoInput) (*model.Video, error) {
	// Parse UUID
	videoID, err := uuid.Parse(id)
	if err != nil {
		return nil, fmt.Errorf("invalid video ID: %w", err)
	}

	// Get existing video
	existingVideo, err := r.VideoService.GetByID(id)
	if err != nil {
		return nil, fmt.Errorf("video not found: %w", err)
	}

	// Update fields if provided
	if input.Title != nil {
		existingVideo.Title = *input.Title
	}
	if input.Description != nil {
		existingVideo.Description = *input.Description
	}
	if input.URL != nil {
		existingVideo.URL = *input.URL
	}

	existingVideo.ID = videoID

	// Call service
	updatedVideo, err := r.VideoService.Update(*existingVideo)
	if err != nil {
		return nil, fmt.Errorf("failed to update video: %w", err)
	}

	return videoEntityToModel(&updatedVideo), nil
}

// DeleteVideo is the resolver for the deleteVideo field.
func (r *mutationResolver) DeleteVideo(ctx context.Context, id string) (bool, error) {
	err := r.VideoService.Delete(id)
	if err != nil {
		return false, fmt.Errorf("failed to delete video: %w", err)
	}
	return true, nil
}

// Videos is the resolver for the videos field.
func (r *queryResolver) Videos(ctx context.Context) ([]*model.Video, error) {
	videos, err := r.VideoService.GetAll()
	if err != nil {
		return nil, fmt.Errorf("failed to fetch videos: %w", err)
	}

	// Convert entities to GraphQL models
	result := make([]*model.Video, len(videos))
	for i, video := range videos {
		result[i] = videoEntityToModel(&video)
	}

	return result, nil
}

// Video is the resolver for the video field.
func (r *queryResolver) Video(ctx context.Context, id string) (*model.Video, error) {
	video, err := r.VideoService.GetByID(id)
	if err != nil {
		return nil, fmt.Errorf("video not found: %w", err)
	}
	return videoEntityToModel(video), nil
}

// Helper function to convert entity.Video to model.Video
func videoEntityToModel(v *entity.Video) *model.Video {
	return &model.Video{
		ID:          v.ID.String(),
		Title:       v.Title,
		Description: v.Description,
		URL:         v.URL,
		Author: &model.Person{
			ID:        v.Author.ID.String(),
			Name:      v.Author.Name,
			Age:       int32(v.Author.Age),
			Email:     v.Author.Email,
			CreatedAt: v.Author.CreatedAt.Format(time.RFC3339),
			UpdatedAt: v.Author.UpdatedAt.Format(time.RFC3339),
		},
		CreatedAt: v.CreatedAt.Format(time.RFC3339),
		UpdatedAt: v.UpdatedAt.Format(time.RFC3339),
	}
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *mutationResolver) CreateTodo(ctx context.Context, input model.NewTodo) (*model.Todo, error) {
	panic(fmt.Errorf("not implemented: CreateTodo - createTodo"))
}
func (r *queryResolver) Todos(ctx context.Context) ([]*model.Todo, error) {
	panic(fmt.Errorf("not implemented: Todos - todos"))
}
*/
