// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateVideoInput struct {
	Title       string       `json:"title"`
	Description string       `json:"description"`
	URL         string       `json:"url"`
	Author      *PersonInput `json:"author"`
}

type Mutation struct {
}

type Person struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Age       int32  `json:"age"`
	Email     string `json:"email"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

type PersonInput struct {
	Name  string `json:"name"`
	Age   int32  `json:"age"`
	Email string `json:"email"`
}

type Query struct {
}

type UpdateVideoInput struct {
	Title       *string `json:"title,omitempty"`
	Description *string `json:"description,omitempty"`
	URL         *string `json:"url,omitempty"`
}

type Video struct {
	ID          string  `json:"id"`
	Title       string  `json:"title"`
	Description string  `json:"description"`
	URL         string  `json:"url"`
	Author      *Person `json:"author"`
	CreatedAt   string  `json:"createdAt"`
	UpdatedAt   string  `json:"updatedAt"`
}
